erDiagram
  USERS {
    BIGINT id PK
    VARCHAR name
    VARCHAR email
    TIMESTAMP email_verified_at
    VARCHAR password
    VARCHAR remember_token
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

erDiagram
  CATEGORIES {
    BIGINT id PK
    VARCHAR content
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

erDiagram
  CONTACTS {
    BIGINT id PK
    VARCHAR first_name
    VARCHAR last_name
    TINYINT gender
    VARCHAR email
    VARCHAR tel
    VARCHAR address
    VARCHAR building
    BIGINT category_id FK
    VARCHAR detail
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  CATEGORIES ||--o{ CONTACTS : "1:N"


